### PR TITLE
chore: migration to new name CGUs -> OpenTermsArchive

### PR DESCRIPTION
**Pull request by martinratinaud**

### CODE REVIEW

**Comment by martinratinaud** [comment]
@vviers please review and merge this request when you can

Thanks

**Review by vviers — CHANGES_REQUESTED** [review]
LGTM :) _but_ can you merge this PR into `refacto/automate-dataset-update` instead of `main` please ?

**Comment by martinratinaud** [comment]
@vviers done, I let you merge it?

**Comment by vviers** [comment]
> @vviers done, I let you merge it?

I think you need to update the repo URL in `Dockerfile` and then yes I'll merge it ! Thanks 🙂

**Comment by martinratinaud** [comment]
@vviers not sure what you mean, I do not see any change on Dockerfile now.
Can you please point me to the change
Thanks

**Comment by vviers** [comment]
@martinratinaud sorry I forgot about the refacto
the lines that needs change are :
https://github.com/ambanum/OpenTermsArchive-api/blob/08a69cdf7643dc5618b02b13ee01c4ccf4ede133/download_dataset.sh#L2

and 

https://github.com/ambanum/OpenTermsArchive-api/blob/08a69cdf7643dc5618b02b13ee01c4ccf4ede133/check_for_data.sh#L2

**Comment by martinratinaud** [comment]
My bad, didn't see
Should be ok now

Also I changed in dataset_parser.py https://github.com/ambanum/OpenTermsArchive-api/blob/ac52f42096db1aa28f301209d6a94ae4518e9313/app/dataset_parser.py#L15

**Review by vviers — APPROVED** [review]
LGTM :)

**Pull request merged**
